spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  jpa:
    database: mysql
    show-sql: true 
    generate-ddl: false
    hibernate: 
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        format_sql: true
        type: trace
  datasource:
    url: jdbc:mysql://localhost:33060/dbs?useSSL=false
    username: root
    password: 12345
        
logging:
  level:
    org:
      hibernate: 
        type:  
          descriptor: 
            sql: 
              BasicBinder: TRACE 
